var fixture = {
  module: "root",
  children: [
    {
      "module":"section",
      "children":
        [
          {
             "module":"header",
          },
          {
             "module":"paragraph",
          },
          {
             "module":"image",
          },
          {
            "module":"section",
            "children":
              [
                {
                   "module":"header",
                },
                {
                   "module":"paragraph",
                },
                {
                   "module":"image",
                }
              ]
          },
        ]
    },
    {
      "module":"section",
      "children":[
        {
           "module":"column",
        },
        {
           "module":"video",
        }
      ]
    },
    {
      "module":"image"
    },
  ]
}
